version: '3'
services:
  service:
    build: .
    platform: linux/amd64
    expose:
      - "8000"
  
  # Elasticsearch - https://geshan.com.np/blog/2023/06/elasticsearch-docker/
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  # Data Base configiration - https://learndjango.com/tutorials/django-docker-and-postgresql-tutorial
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  tests:
    entrypoint: >
      sh -c "pip install -r /tests/functional/requirements.txt
      && python3 /tests/functional/utils/wait_for_es.py
      && python3 /tests/functional/utils/wait_for_redis.py
      && pytest /tests/functional/src"
      
volumes:
  cache:
    driver: local


